include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-dynamic: true
    implicit-casts: true

  errors:
    avoid_dynamic_calls: error
    missing_required_param: error
    missing_return: error
    todo: info
    missing_enum_constant_in_switch: error
    invalid_use_of_protected_member: error
    unused_local_variable: warning
    deprecated_member_use: warning
    unused_element: warning
    unused_field: warning
    dead_code: error
    must_call_super: error

    # linter errors
    unnecessary_statements: error
    recursive_getters: ignore
    unnecessary_new: error
    unnecessary_getters_setters: error
    use_function_type_syntax_for_parameters: error
    no_duplicate_case_values: error
    no_adjacent_strings_in_list: error
    non_constant_identifier_names: error
    constant_identifier_names: error
    avoid_returning_this: error
    prefer_const_constructors_in_immutables: error
    prefer_const_literals_to_create_immutables: error
    avoid_equals_and_hash_code_on_mutable_classes: error
    camel_case_types: error
    camel_case_extensions: error
    library_names: error
    file_names: error
    library_prefixes: error

    # linter warnings
    avoid_print: warning
    unnecessary_lambdas: warning
    use_key_in_widget_constructors: warning
    prefer_final_fields: warning
    prefer_final_locals: warning
    prefer_final_in_for_each: warning
    prefer_const_constructors: warning
    unnecessary_const: warning
    unnecessary_brace_in_string_interps: warning

  exclude:
    - "bin/cache/**"
    - "**/*.chopper.dart"
    - "**/generated/**"
    - "**/gen/**"
    - "**/*.g.dart"
    - "**/*.mocks.dart"
    - "**/*.freezed.dart"
    - "**/strings/**/*"

  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true

formatter:
  trailing_commas: preserve
